name: 🚀 New Project Submission
description: Submit a new project to OpenPlayground
title: "[New Project]: "
labels: ["new-project", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Want to add a project? Great! Fill out this form and then submit a PR.
        
        **Before submitting:**
        - Make sure your project uses vanilla HTML, CSS, and JavaScript
        - Test your project locally
        - Read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines

  - type: input
    id: project_name
    attributes:
      label: Project Name
      placeholder: e.g., "Weather Dashboard"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - utility
        - game
        - puzzle
        - fun
        - productivity
        - experimental
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: Brief description (max 100 characters for card display)
      placeholder: A weather app that shows current conditions and forecasts.
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Key Features
      placeholder: |
        - Feature 1
        - Feature 2
        - Feature 3

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots of your project
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: My project uses vanilla HTML, CSS, and JavaScript
          required: true
        - label: I have tested my project locally
          required: true
        - label: My project is responsive
          required: true
        - label: I will add my project to projects.json (NOT index.html)
          required: true
